### ISSUE TITLE
About  generalization experiments on Middlebury and ETH3D.

### ISSUE THREAD

**Issue by Zhaohuai-L** [gangweiX/IGEV#1]
Hi,thank you very much for your great work.  
I test the generalization performance of the checkpoint you provided on Middlebury and ETH3D, but the results are different from Table7.
Is it because the checkpoint provided is training without data augmentation ?
**So i would like to know if i misunderstood or misused? Thanks.**

The checkpoint for test is [sceneflow.pth](https://drive.google.com/drive/folders/1yqQ55j8ZRodF1MZAI6DAXjjre3--OYOX)

The results on Middlebury(half) training sets is :
All:
'EPE': [7.572738313674927], 'D1': [0.27418503363927205], 'Thres1': [0.4556864986817042], 'Thres2': [0.3513654222091039], 'Thres3': [0.3013058652480443]
Noc:
avg_test_scalars_nonocc {'EPE': [6.537938332557678], 'D1': [0.2406569098432859], 'Thres1': [0.41864077051480614], 'Thres2': [0.3155737062295278], 'Thres3': [0.2668188696106275]}

The results on ETH3D training sets is :
All:
'EPE': [0.9156075097896434], 'D1': [0.06998444140157921], 'Thres1': [0.18718870177313132], 'Thres2': [0.10728459610362295], 'Thres3': [0.06998444140157921]
Noc:
'EPE': [0.9049188627137078], 'D1': [0.06913529045548919], 'Thres1': [0.1841263070150658], 'Thres2': [0.10554461269768783], 'Thres3': [0.06913529045548919]

The results in Table7 is : 
![image](https://user-images.githubusercontent.com/62138387/225694641-148fe497-7a35-450a-a66a-c58f258dcdef.png)

Some qualitative results about the checkpoint:

![color_disp](https://user-images.githubusercontent.com/62138387/225699963-9dadb62a-9a4d-4fb5-988c-13ab2eede66a.png)

![playground_1l](https://user-images.githubusercontent.com/62138387/225700142-806de42c-ec85-4e10-8ef8-8094df4f27cf.png)

 
BTW,I am also curious about how the results of RAFT-Stereo in Table 7 are obtained?
![image](https://user-images.githubusercontent.com/62138387/225697454-eac91516-b9fe-40c0-a909-c88ed29da383.png)

The generalization result in the RAFT-Stereo paper is：
![image](https://user-images.githubusercontent.com/62138387/225698283-402ea21f-cf13-4218-882c-86660e471185.png)

The results in Graftnet are the same as RAFT-Stereo:
![image](https://user-images.githubusercontent.com/62138387/225698871-95dd6df4-91a2-4d9c-bfe7-993f8560028f.png)

**Comment by gangweiX** [comment]
Thank you for your attention.
You can run evaluate_stereo.py to test generalization on Middlebury and ETH3D.
We use 15 training pairs of Middlebury 2014 and 27 training pairs of ETH3D to test generalization.
![image](https://user-images.githubusercontent.com/34023118/225802377-2e8f405d-1f8a-4aed-8529-7ed270d42c18.png)

![image](https://user-images.githubusercontent.com/34023118/225802796-8f424654-78ca-4076-9694-cdc7ad4723d4.png)

**Comment by Zhaohuai-L** [comment]
Thank you for your reply. I reprodueced the results using that code, such an amazing work.

**Comment by jiayuzhang128** [comment]
such an amazing work!

**Comment by killwy** [comment]
I am also curious about how the results of RAFT-Stereo in Table 7 are obtained? There are some differences between your paper and RAFT-Stereo raw paper.

**Comment by gangweiX** [comment]
Thank you for your attention, our evaluation method is different from RAFT-Stereo in Table 7, please refer to our code, we evaluate the non-occluded regions.

**Comment by killwy** [comment]
Thanks for your response!
