### ISSUE TITLE
max disparity can't be changed

### ISSUE THREAD

**Issue by gutcBrEl** [gangweiX/IGEV#14]
Hi

Many thanks for your work!

It seems that the _max_disp_ parameter, which is set to 192 per default, can not be changed.
Change this value will cause a shape mismatch.

I figured out, this shape mismatch can be avoided by changing [this line](https://github.com/gangweiX/IGEV/blob/main/IGEV-Stereo/core/igev_stereo.py#L168) to:
`gwc_volume = build_gwc_volume(match_left, match_right, self.args.max_disp//4, 8)`
However igev stereo still is not able to match disparities > 192 pixels.

Do I neet to retrain the network with this change?

Best regards

**Comment by gangweiX** [comment]
Yeah, you need to retrain the network.

**Comment by gangweiX** [comment]
When you change max disparity to >192, such as 256 or 384, the igev stereo is still able to obtain accurate matches, you may not retrain the network. However, retraining may give better results for disparities > 192 pixels.
