### ISSUE TITLE
About the performance on ETH3D

### ISSUE THREAD

**Issue by StereoResearcher** [gangweiX/IGEV#18]
Dear Dr.Xu:
You did a fantastic job on this project! Thank you for sharing your work.
I would like to ask you a question regarding ETH3D. Your evaluation score  (3.6) for the ETH3D training set is more modest than RAFT-Stereo's score (3.2), but your experiments outperform RAFT-Stereo in the ETH3D online benchmark (You rank 4th and RAFT ranks 62nd). Could you please teach me why you can perform better now?
Thank you very much!

**Comment by gangweiX** [comment]
Thanks for your attention. We use more data to train our network, our training data and plan are consistent with unimatch, please refer to https://github.com/autonomousvision/unimatch
