### ISSUE TITLE
cannot find the disp0GT.pfm in Middlebury

### ISSUE THREAD

**Issue by zuixiaosanlang** [gangweiX/IGEV#20]
![image](https://github.com/gangweiX/IGEV/assets/20105627/32dd5d56-7358-4d8e-b577-b0d52c7633f4)

there is no disp0GT.pfm.

![image](https://github.com/gangweiX/IGEV/assets/20105627/0b678797-8868-4723-b66b-cdb8994e956a)

also, no mask0nocc.png.

**Comment by gangweiX** [comment]
See https://vision.middlebury.edu/stereo/submit3/
![image](https://github.com/gangweiX/IGEV/assets/34023118/d1884add-a1a6-43d6-bb10-99cab315c36d)

**Comment by zuixiaosanlang** [comment]
@gangweiX 
thanks, i have an other question.

if my dataset is about up and down, not left right,   
does the pipeline still work ??  if not, how to change the code.

thanks.
