### ISSUE TITLE
kitti数据集训练问题

### ISSUE THREAD

**Issue by xcwqaq999** [gangweiX/IGEV#21]
作者您好，我在训练kitti数据集的过程中，发现记载的验证集是FlyingThings的，但是我在evaluate_stereo.py里面已经将dataset改为kitti了，我找不到原因，麻烦您解答一下。

**Comment by gangweiX** [comment]
你需要在train_stereo.py里面进行修改，在187行，把results = validate_sceneflow(model.module, iters=args.valid_iters)中的validate_sceneflow改成validate_kitti

**Comment by xcwqaq999** [comment]
谢谢作者！再次感谢您优秀的作品！
