### ISSUE TITLE
Questions about MVS training

### ISSUE THREAD

**Issue by pnpmpnp** [gangweiX/IGEV#26]
First, thank you for sharing this great research.

I have a question regarding MVS training.
When training MVS, despite having GT Depth, is there a reason to convert it to disparity level and lose it?

When I was training, I noticed that borrowing the RAFT structure, applying loss at depth level doesn't work, but applying loss at disparity level works.

Do you have any idea why this is the case?

Thanks again.

**Comment by gangweiX** [comment]
I also tried to use depth supervision before, but it didn't work, and then I changed to disparity supervision. I refer to IterMVS https://github.com/FangjinhuaWang/IterMVS

**Comment by pnpmpnp** [comment]
Thanks for the quick reply and once again for sharing your great research. 

I will close the issue.
