### ISSUE TITLE
有关模型训练的一些问题

### ISSUE THREAD

**Issue by Yu-Cheung** [gangweiX/IGEV#30]
作者您好！
我直接使用`KITTI Dataset`来训练模型，但是我发现我的模型在训练到`800steps`时，他的`Loss`降到了`14`，但是继续训练后，他的`Loss`直接会升到`200`左右，并且再也没降下来。
然后这是我的Loss图像，我想知道这是什么原因。谢谢！
![image](https://github.com/gangweiX/IGEV/assets/66195010/ae5ea2ef-9181-470c-9f13-c43dbbfbb6e7)

**Comment by gangweiX** [comment]
我没有直接在KITTI上训练，所以我不太了解这个问题

**Comment by Yu-Cheung** [comment]
我用scene flow训练的时候也是这种情况，并没有修改源码。然后我也看了Issues里，也有人提出了这个问题，Loss会降低后立马上升，并且验证的epe也会提高
