### ISSUE TITLE
如何得到深度图？

### ISSUE THREAD

**Issue by PatrickSDUST** [gangweiX/IGEV#35]
你好，请问如何根据视差得到深度图呢，感谢！

**Comment by gangweiX** [comment]
你好，想要获得深度图，除了知道视差图之外，还需要知道双目相机的基线b和焦距f，根据立体视觉中的三角测量原理。深度depth = (b*f) / (disparity)

**Comment by zhangjy328** [comment]
@gangweiX 大佬，有没有转换的脚本？能分享一下吗？
