### ISSUE TITLE
自己重新训练数据集时出现问题

### ISSUE THREAD

**Issue by Yu-Cheung** [gangweiX/IGEV#38]
我用 $Scene \ Flow$ 数据集从零开始训练， $Loss$ 一直在上升，同时 $EPE$ 也在上升，并且  $Loss$  和  $EPE$  在最后都会直接收敛。是数据集出现问题了吗？然后这是我训练时候的  $Loss$  和  $EPE$。对于整个网络，我只修改了数据集读取的路径，是不是我的数据集本身出现问题了？
![image](https://github.com/gangweiX/IGEV/assets/66195010/00c39dfa-c33f-4c0d-8ffc-ba24febd3c2c)
![image](https://github.com/gangweiX/IGEV/assets/66195010/33facfb8-1234-43b9-a771-88efd2ed5ef4)

**Comment by gangweiX** [comment]
不明白，我从来没有出现过这种情况。你一直都是这种情况嘛？

**Comment by Windsrain** [comment]
我重新从github上下载了最新代码进行训练，目前跑了5k steps没有任何问题。
![JT{5`4%EYJ0_X0XG` %O50L](https://github.com/gangweiX/IGEV/assets/43723173/389706df-3311-4c12-bf5e-3be79545727e)
