### ISSUE TITLE
关于demo_imgs.py相关的问题

### ISSUE THREAD

**Issue by Asurasin** [gangweiX/IGEV#4]
@gangweiX 作者您好，我在进行demo图片测试的时候，报出以下错误：
![image](https://user-images.githubusercontent.com/66195010/229780033-5d1acd63-5e7e-43bb-b728-b51a641bbc30.png)
当我对报错区域进行初始化后
![image](https://user-images.githubusercontent.com/66195010/229780591-1057b13c-3159-47e0-b769-c0e94faaed39.png)
又会出现如下的错误
![image](https://user-images.githubusercontent.com/66195010/229780643-e1b3d294-dece-4a03-9133-76d467cb7547.png)
请问应该如何解决

**Comment by gangweiX** [comment]
请问你现在解决了吗？

**Comment by gangweiX** [comment]
请问你解决了吗
2023-04-04 19:42:05>Asurasin 写道：

@gangweiX 作者您好，我在进行demo图片测试的时候，报出以下错误：

当我对报错区域进行初始化后

又会出现如下的错误

请问应该如何解决

**Comment by Asurasin** [comment]
谢谢作者的回复，已经解决了，可能是在进行代码注释的时候改了一些代码，导致程序报错
