### ISSUE TITLE
kitti2012以及kitti2015的checkpoint的区别

### ISSUE THREAD

**Issue by jiaw-z** [gangweiX/IGEV#40]
作者您好，我想问一下所提供的在kitti上的两个checkpoint，kitti2012和kitti2015的区别。
论文里面写到的是在12和15的混合训练集上进行fine-tune，那应该两个数据集共享一个checkpoint
希望您可以提供一些这两个checkpoint的训练细节，谢谢

**Comment by gangweiX** [comment]
嗨，你好，在混合训练后，我分别测试了几个checkpoint，分别挑选了针对kitti2012和kitti2015最好的一个
