### ISSUE TITLE
图像输入大小

### ISSUE THREAD

**Issue by Luckyangle1232** [gangweiX/IGEV#47]

**Comment by gangweiX** [comment]
Hi

在训练的时候应该是[320, 736]，在测试的时候是960*540。训练的时候，为了增加训练速度，防止显存过大，会对图片进行一个随机crop。测试的时候一般用原始的图片大小。

Gangwei Xu2023-12-08 09:21:21>Wade_Lucky 写道：

作者您好，我想和您咨询一下关于图像输入的问题。在Scene Flow中，您以[320,736 ]作为输入的，我看您在消融实验中，将输入调整为960*540，能否请教一下，以原来的输入图像大小进行消融和新的 图像大小进行消融是否有区别？
