### ISSUE TITLE
视差图着色

### ISSUE THREAD

**Issue by Luckyangle1232** [gangweiX/IGEV#54]
作者您好，很不好意思，又来打扰您。我想咨询一下这个视差图着色用什么样的参数比较合适，尝试了好几个不尽如人意，可否分享一下您的此部分代码。注：我在写的文章已引用您的文章

**Comment by gangweiX** [comment]
我使用的视差图着色代码在https://github.com/gangweiX/IGEV/blob/main/IGEV-Stereo/demo_imgs.py中的第52行，即
plt.imsave(output_directory / f"{file_stem}.png", disp.squeeze(), cmap='jet')，如果是cv2.imwrite的话，则是
cv2.imwrite(filename, cv2.applyColorMap(cv2.convertScaleAbs(disp.squeeze(), alpha=0.01),cv2.COLORMAP_JET), [int(cv2.IMWRITE_PNG_COMPRESSION), 0])。方便的话，可以把我的几篇论文都引用一下，应该是和你的论文主题一致的，如果不一致就算了

**Comment by Luckyangle1232** [comment]
> 我使用的视差图着色代码在[https://github.com/gangweiX/IGEV/blob/main/IGEV-Stereo/demo_imgs.py中的第52行，即](https://github.com/gangweiX/IGEV/blob/main/IGEV-Stereo/demo_imgs.py%E4%B8%AD%E7%9A%84%E7%AC%AC52%E8%A1%8C%EF%BC%8C%E5%8D%B3) plt.imsave(output_directory / f"{file_stem}.png", disp.squeeze(), cmap='jet')，如果是cv2.imwrite的话，则是 cv2.imwrite(filename, cv2.applyColorMap(cv2.convertScaleAbs(disp.squeeze(), alpha=0.01),cv2.COLORMAP_JET), [int(cv2.IMWRITE_PNG_COMPRESSION), 0])。方便的话，可以把我的几篇论文都引用一下，应该是和你的论文主题一致的，如果不一致就算了

ACVNet和IGEV都引用了，感谢您的帮助
