### ISSUE TITLE
Runtime is not matching as mentioned in the paper

### ISSUE THREAD

**Issue by snehahegdek** [gangweiX/IGEV#61]
Hello,

Firstly, I want to express my appreciation for your excellent work and the valuable contribution you've made to the field.

I recently had the opportunity to implement your method and evaluate its performance on the **Kitti2015 dataset** using the evaluate.py script. However, I noticed a discrepancy in the runtime compared to the values reported in your paper. While your paper indicates a runtime of **0.18s**, my evaluation on **an NVIDIA RTX 3090 GPU** card yielded a runtime of **0.29s**.

Any additional information or parameters that might influence the runtime would be immensely helpful.

Thank you very much for your time, and I appreciate any assistance you can provide. I look forward to hearing from you soon.

**Comment by gangweiX** [comment]
Thanks for your attention. The runtime is tested using 16 iterations. I mentioned the measurement of runtime in my paper.

**Comment by gangweiX** [comment]
On KITTI 15 benckmark, the results (D1-all: 1.59) of 16 iters and 32 iters are consistent. So we use the result of 16 iters.

**Comment by snehahegdek** [comment]
Thank you for the quick reply. I was able to reproduce the same runtime after revisiting the implementation.
