### ISSUE TITLE
关于IGEV加载预训练权重失败的问题？

### ISSUE THREAD

**Issue by Hlll-huang** [gangweiX/IGEV#79]
我从本地加载了预训练权重
model = timm.create_model('mobilenetv2_100', pretrained=True, features_only=True, pretrained_cfg_overlay=dict(file='mobilenetv2_100/pytorch_model.bin'))

出现报错：
  File "E:\IGEV-main\IGEV-Stereo\core\extractor.py", line 342, in __init__
    self.act1 = model.act1
  File "D:\anaconda3\envs\raftstereo\lib\site-packages\torch\nn\modules\module.py", line 1186, in __getattr__
    type(self).__name__, name))
AttributeError: 'EfficientNetFeatures' object has no attribute 'act1'

想烦请大家帮忙解决一下

**Comment by gangweiX** [comment]
可能是你安装的timm版本不对，导致加载时候模型的名字不一致，你可以安装和相对应的timm版本：pip install timm==0.5.4

**Comment by Hlll-huang** [comment]
好的，谢谢您
