### ISSUE TITLE
数据集路径疑问

### ISSUE THREAD

**Issue by yubinyb** [gangweiX/IGEV#86]
您好，请问能否对文档中说的数据集路径再详细说明下。

sceneflow数据集是把flying、monkaa 和driving三个合并到一起了吗？
下载KITTI_2012和2015数据集后，发现其中的training、testing底下还有很多子文件夹（如下图），需要把它们的内容放到一个统一的就叫做training或者testing的文件夹底下吗，还是说不需要动呢？另外 vkitti 文件夹是哪一项呢，下载KITTI数据集后有一个calib文件夹需要用到吗？
![image](https://github.com/user-attachments/assets/8a90782e-1b4a-40aa-b203-c7eced293837)

**Comment by gangweiX** [comment]
sceneflow数据集是把flying、monkaa 和driving三个合并到一起了
![image](https://github.com/user-attachments/assets/e060401c-d30d-4d23-9089-0711eec37674)

KITTI数据集文件夹折叠方式如下：
![image](https://github.com/user-attachments/assets/57e88526-b074-4758-9252-20e757e69cf1)
calib文件夹不需要用到
