### ISSUE TITLE
为什么GridSample的第三维度设置为1

### ISSUE THREAD

**Issue by SSHLR** [gangweiX/IGEV#89]
您好，我遇到一个问题，给bilinear_sampler输入的参数geo_volume维度为（b * h * w , c, 1, d），这里为什么要求第3维度是1,注释中# This is a stereo problem是什么意思呢？第3维度大于1会有什么问题呢？

https://github.com/gangweiX/IGEV/blob/52ee453d45c88b8235a22142f275329cd72d5fc9/IGEV-Stereo/core/geometry.py#L46

https://github.com/gangweiX/IGEV/blob/52ee453d45c88b8235a22142f275329cd72d5fc9/IGEV-Stereo/core/utils/utils.py#L64

**Comment by gangweiX** [comment]
由于志在视差维度上索引代价值，因此第三维度设置为1。如果第三维度不设置成1，则也会在第三维度上索引，但显然这是没有意义的。可以参考RAFT，如果是二维搜索匹配点，则会在第三维度上也进行索引，立体匹配只是一维搜索匹配点（即沿着水平线）

**Comment by SSHLR** [comment]
谢谢，明白了
