### ISSUE TITLE
This may be an issue with the path of the dataset

### ISSUE THREAD

**Issue by billie2jean** [gangweiX/IGEV#91]
Hi, I run `python train_stereo.py --logdir ./checkpoints/sceneflow`, but there is something wrong:
![image](https://github.com/user-attachments/assets/23c4004d-2172-4c83-8232-2603923a01cd)
This may be an issue with the path of the dataset, I set up the dataset directory the way you did, but the problem remains.

**Comment by gangweiX** [comment]
<img width="876" alt="image" src="https://github.com/user-attachments/assets/016a8d0e-5c1e-445b-9493-86026836bc66">

You need to set the dataset path (https://github.com/gangweiX/IGEV/blob/main/IGEV-Stereo/core/stereo_datasets.py) to your own. The '/data/sceneflow/' needs to be set to your own.

**Comment by billie2jean** [comment]
Thanks! I successfully solved this problem.
